Models/Chamado.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace AplicativoChamados.Models {
	public class Chamado {
		public int chamadoId { get; set; }
		public DateTime dataAbertura { get; set; }
		public DateTime dataAtendimento { get; set; }
		public string descricaoDoChamado { get;set; }
		public string descicaoAtendimento { get; set; }
		public string situacao { get; set; }
		public int usuarioId { get; set; }

		[NotMapped] 
		public string NomeDoUsuario { get; set; }

	}
}

Models/Usuario.cs
namespace AplicativoChamados.Models {
	public class Usuario {
		public int usuarioId { get; set; }
		public string nomeCompleto { get; set; }
	}
}

Controllers/ChamadosController.cs
using AplicativoChamados.DAO;
using AplicativoChamados.Models;
using Microsoft.AspNetCore.Mvc;

namespace AplicativoChamados.Controllers
{
    public class ChamadosController : Controller{
		private readonly ChamadosDAO _chamadosDAO;
		private readonly UsuariosDAO _usuariosDAO;

		public ChamadosController(ChamadosDAO chamadosDAO, UsuariosDAO usuariosDAO) {
			_chamadosDAO = chamadosDAO;
			_usuariosDAO = usuariosDAO;
		}

        public IActionResult Index(){
			var chamados = _chamadosDAO.Listagem();

			foreach(var chamado in chamados) {
				var usuario = _usuariosDAO.ProcurarPorId(chamado.usuarioId);
				chamado.NomeDoUsuario = usuario?.nomeCompleto;
			}

			return View(chamados);
        }
		public IActionResult CriarChamado() {
			return View();
		}
		public IActionResult Salvar() {
			return View();
		}

		public IActionResult Detalhes() {
			return View();
		}

        public IActionResult Visualizar() {
			return View();
		}

		public IActionResult Alterar() {
			return View();
		}

		public IActionResult Edit() {
			return View();
		}

		public IActionResult Remover() {
			return View();
		}
	}
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AplicativoChamados.Models;
using AplicativoChamados.ViewModel;

namespace AplicativoChamados.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/UsuariosController.cs
using AplicativoChamados.DAO;
using AplicativoChamados.Models;
using Microsoft.AspNetCore.Mvc;

namespace AplicativoChamados.Controllers
{
    public class UsuariosController : Controller
    {
		private readonly UsuariosDAO _usuariosDAO;

		public UsuariosController(UsuariosDAO usuariosDAO) {
			_usuariosDAO = usuariosDAO;
		}

        public IActionResult Index(){
			List<Usuario> usuarios = _usuariosDAO.Listagem();

            return View(usuarios);
        }

		[HttpGet]
		public IActionResult CriarUsuario() {
			var model = new Usuario();

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Salvar(Usuario user) {
			user.usuarioId = _usuariosDAO.ProximoId();

			if (ModelState.IsValid) {
				_usuariosDAO.Inserir(user);
				return RedirectToAction("Index");
			}

			return View("CriarUsuario", user);
		}


		[HttpGet]
		public IActionResult Visualizar(int usuarioId) {
			var usuario = _usuariosDAO.ProcurarPorId(usuarioId);
			if (usuario == null)
				return NotFound();

			return View(usuario);
		}

		public IActionResult Alterar(int usuarioId) {
			var usuario = _usuariosDAO.ProcurarPorId(usuarioId);

			if (usuario == null)
				NotFound();

			return View(usuario);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Atualizar(Usuario user) {
			if (ModelState.IsValid) {
				_usuariosDAO.Alterar(user);
				return RedirectToAction("Index");
			}
			return View(user);
		}

		public IActionResult Remover(int usuarioId) {
			_usuariosDAO.Remover(usuarioId);

			List<Usuario> usuarios = _usuariosDAO.Listagem();

			return View("Index", usuarios);
		}
	}
}

Views/Chamados/Alterar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Chamados/CriarChamado.cshtml
@model AplicativoChamados.Models.Usuario

<h1>Criar Chamado</h1>

<form method="post" asp-action="Salvar" novalidate>
    <h3>Dados do Chamado</h3>
    <div class="form-group">
        <label for="nome">Nome Completo</label>
        <input type="text" class="form-control" id="nomeCompleto" name="nomeCompleto" value="@Model.nomeCompleto" />
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

<a href="@Url.Action("Index", "Usuarios")">Voltar para os usuarios</a>

Views/Chamados/Index.cshtml
@model List<AplicativoChamados.Models.Chamado>

<div>
    <h1>Bem-Vindos ao gerenciador de chamados da FESA</h1>

    <p>Meus chamados atribuidos: XX</p>

    <a class="btn btn-info" asp-controller="Chamados" asp-action="CriarChamado">Novo Chamado</a>

    <div class="row">
        @if (Model != null && Model.Any()) {
            foreach (var infoChamado in Model) {
                <partial name="_chamadoResumo" for="@infoChamado" />
            }
        }
        else {
            <p>Não há chamados cadastrados.</p>
        }
    </div>
</div>

Views/Chamados/Visualizar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <a class="btn btn-primary" asp-controller="Chamados" asp-action="Index">FESA Chamados</a>
</div>

<div class="text-center">
    <a class="btn btn-secondary" asp-controller="Usuarios" asp-action="Index">FESA Usuários</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicativoChamados</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicativoChamados.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AplicativoChamados</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - AplicativoChamados - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_chamadoResumo.cshtml
@model AplicativoChamados.Models.Chamado;

<div class="col-sm-4 col-md-4 col-xl-4">
    <a asp-controller="Chamado" asp-route-chamadoId="@Model.chamadoId" class="text-decoration-none text-dark">
        <br />
        <div class="border rounded p-3">
            <h5>@Model.descricaoDoChamado</h5>
            <h4>@Model.situacao</h4>
            @if(Model.situacao == "Atendido"){
                <p>@Model.NomeDoUsuario</p>
            }
            <div>
                <p class="button">
                    <a class="btn btn-primary" id="cartButton" asp-controller="Chamados" asp-action="Visualizar" asp-route-chamadoId="@Model.chamadoId">Visualizar</a>
                    <a class="btn btn-secundary" id="cartButton" asp-controller="Chamados" asp-action="Remover" asp-route-chamadoId="@Model.chamadoId">Excluir</a>
                    <a class="btn btn-secundary" id="cartButton" asp-controller="Chamados" asp-action="Alterar" asp-route-chamadoId="@Model.chamadoId">Editar</a>
                </p>
            </div>
        </div>
    </a>
</div>

Views/Shared/_usuarioResumo.cshtml
@model AplicativoChamados.Models.Usuario

<div class="col-sm-4 col-md-4 col-xl-4">
    <a asp-controller="Usuarios" asp-route-chamadoId="@Model.usuarioId" class="text-decoration-none text-dark">
        <br />
        <div class="border rounded p-3">
            <h5>@Model.usuarioId</h5>
            <h4>@Model.nomeCompleto</h4>
            <div>
                <p class="button">
                    <a class="btn btn-primary" id="cartButton" asp-controller="Usuarios" asp-action="Visualizar" asp-route-usuarioId="@Model.usuarioId">Visualizar</a>
                    <a class="btn btn-secundary" id="cartButton" asp-controller="Usuarios" asp-action="Remover" asp-route-usuarioId="@Model.usuarioId">Excluir</a>
                    <a class="btn btn-secundary" id="cartButton" asp-controller="Usuarios" asp-action="Alterar" asp-route-usuarioId="@Model.usuarioId">Editar</a>
                </p>
            </div>
        </div>
    </a>
</div>

Views/Usuarios/Alterar.cshtml
@model AplicativoChamados.Models.Usuario

<h1>Editar Usuário</h1>

<form method="post" asp-action="Atualizar" novalidate>
    <input type="hidden" asp-for="usuarioId" />

    <h3>Dados do Usuario</h3>
    <div class="form-group">
        <label for="nome">Nome Completo</label>
        <input type="text" class="form-control" id="nomeCompleto" name="nomeCompleto" value="@Model.nomeCompleto" />
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

<a href="@Url.Action("Index", "Usuarios")">Voltar para os usuarios</a>

Views/Usuarios/CriarUsuario.cshtml
@using AplicativoChamados.Models
@model Usuario

<h1>Criar Usuário</h1>

<form method="post" asp-action="Salvar" novalidate>
    <h3>Dados do Usuario</h3>
    <div class="form-group">
        <label for="nome">Nome Completo</label>
        <input type="text" class="form-control" id="nomeCompleto" name="nomeCompleto" value="@Model.nomeCompleto" />
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

<a href="@Url.Action("Index", "Usuarios")">Voltar para os usuarios</a>

Views/Usuarios/Index.cshtml
@model List<AplicativoChamados.Models.Usuario>

<div>
    <h1>Bem-Vindos ao gerenciador de usuarios da FESA</h1>

    <a class="btn btn-info" asp-controller="Usuarios" asp-action="CriarUsuario">Novo Usuario</a>

    <div class="row">
        @if (Model != null && Model.Any()) {
            foreach (var infoUsuario in Model) {
                <partial name="_usuarioResumo" for="@infoUsuario" />
            }
        }
        else {
            <p>Não há usuarios cadastrados.</p>
        }
    </div>
</div>

Views/Usuarios/Visualizar.cshtml
@model AplicativoChamados.Models.Usuario

@{
    ViewData["Title"] = "Visualizar Usuário";
}

<h2>Visualizar Usuário</h2>

<div class="card mb-3">
    <div class="card-body">
        <p><strong>Nome Completo:</strong> @Model.nomeCompleto</p>
    </div>
</div>

<a asp-controller="Usuarios" asp-action="Index" class="btn btn-secondary">Voltar</a>